services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Gupalo\BpmnWorkflowBundle\Tests\Example\Extension\:
        resource: '../../../tests/Example/Extension/'
        tags:
            - { name: 'bpmnworkflow.extension' }
