services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Gupalo\BpmnWorkflowBundle\Process\Workflow:
        arguments:
            - !tagged_iterator { tag: 'bpmnworkflow.extension' }

    Gupalo\BpmnWorkflowBundle\Extension\:
        resource: '../../Extension/'
        tags:
            - { name: 'bpmnworkflow.extension' }

    Gupalo\BpmnWorkflowBundle\Controller\:
        resource: '../../Controller/'
        tags: [ 'controller.service_arguments' ]

    # repositories
    Gupalo\BpmnWorkflowBundle\Repository\ProcessRepository:
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Gupalo\BpmnWorkflowBundle\Entity\Process
